# Generated by Django 5.2.13 on 2026-04-29 07:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
        ('stitching', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stitchingorder',
            old_name='measurements',
            new_name='extra_measurements',
        ),
        migrations.AddField(
            model_name='stitchingorder',
            name='bottom_width',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='stitchingorder',
            name='chest',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='stitchingorder',
            name='collar',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='stitchingorder',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stitching_orders', to='customers.customer'),
        ),
        migrations.AddField(
            model_name='stitchingorder',
            name='hip',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='stitchingorder',
            name='shalwar_length',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='stitchingorder',
            name='shalwar_waist',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='stitchingorder',
            name='shirt_length',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='stitchingorder',
            name='shoulder',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='stitchingorder',
            name='size',
            field=models.CharField(blank=True, choices=[('20', 'Size 20 (Age 2-3)'), ('22', 'Size 22 (Age 4-5)'), ('24', 'Size 24 (Age 6-7)'), ('26', 'Size 26 (Age 8-9)'), ('28', 'Size 28 (Age 10-11)'), ('30', 'Size 30 (Age 12-13)'), ('32', 'Size 32 (XS)'), ('34', 'Size 34 (S)'), ('36', 'Size 36 (M)'), ('38', 'Size 38 (L)'), ('40', 'Size 40 (XL)'), ('42', 'Size 42 (XXL)'), ('44', 'Size 44 (3XL)'), ('46', 'Size 46 (4XL)'), ('custom', 'Custom Size')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='stitchingorder',
            name='sleeve_length',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='stitchingorder',
            name='waist',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
