# Generated by Django 5.2.13 on 2026-05-22 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stitching', '0002_rename_measurements_stitchingorder_extra_measurements_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stitchingorder',
            name='advance_payment',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='stitchingorder',
            name='code_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
